location          = "eastus2"
department        = "retail"
environment       = "dev"
appname           = "card"
bastion_subnet_id = "/subscriptions/9076ca7f-7f3c-4bab-bbd6-3bf92d79a848/resourceGroups/retail-dev-card-rg/providers/Microsoft.Network/virtualNetworks/retail-dev-card-vnet/subnets/AzureBastionSubnet"